### ISSUE TITLE
Add Multi-OS Download Support

### ISSUE THREAD

**Issue by JamesRy96** [axewater/sharewarez#1]
It would be nice to allow users to download just a particular OS' installer. 

I have a folder called SOMA, inside there are subfolders called Extras, Linux, MacOS and, Windows. The current download button downloads all of the files at 34.27 GB. It would save time, space and bandwidth if the user could select the OS they'd like the download for.

**Comment by axewater** [comment]
the app is setup to give users maximum flexibility in how they store their files. Some people have ISO files, others have 20 rar files in a folder and another person may have all the files extracted. In order to be able to download all these scenarios, we are zipping the folder. I think the best thing to do in your case, is start 1 extra scan inside the SOMA folder. If you already have a SOMA entry, remove that one.

**Comment by axewater** [comment]
ok so I've though about this, and what you are asking for is not doable, without becoming an application that expects a lot from its user. we want to keep this as user friendly as possible, so instead of modifying the app, you will have to use the 'manual game add' feature to add each game.
